# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название отеля')),
                ('slug', models.SlugField(blank=True, default=None, max_length=40, null=True, unique=True)),
                ('address', models.CharField(max_length=256, verbose_name='адрес отеля')),
                ('images', models.ImageField(blank=True, default=None, null=True, upload_to='hotel_images/', verbose_name='фото')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='описание')),
                ('price', models.IntegerField(default=0, verbose_name='цена отеля')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Отели',
                'verbose_name': 'Отель',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='название региона')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='описание региона')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_change', models.DateTimeField(auto_now=True)),
                ('published_region', models.BooleanField(default=False, verbose_name='публикация')),
            ],
            options={
                'verbose_name_plural': 'Регионы',
                'verbose_name': 'Регион',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Region', verbose_name='название региона'),
        ),
    ]
