# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hotel', models.CharField(max_length=256, verbose_name='Название отеля')),
                ('address_hotel', models.CharField(max_length=256, verbose_name='Адрес отеля')),
                ('images_hotel', models.ImageField(upload_to='hotel_images/', verbose_name='Фотография отеля')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Описание отеля')),
                ('price_hotel', models.IntegerField(default=0, verbose_name='Цена отеля')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_change', models.DateTimeField(auto_now=True)),
                ('published_hotel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
                'ordering': ('name_hotel',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_region', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_change', models.DateTimeField(auto_now=True)),
                ('published_region', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ('name_region',),
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Region', verbose_name='Название региона'),
        ),
    ]
