# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='date_of_creation',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='published_region',
            new_name='is_published',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='date_of_change',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='region',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
