# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20170727_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='published_region',
            field=models.BooleanField(default=False, verbose_name='Публикация'),
        ),
    ]
