# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='name_region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.Region'),
        ),
    ]
