# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20170801_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='num',
            field=models.IntegerField(default=0, verbose_name='кол-во опубликованных отелей этого региона'),
        ),
    ]
