# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20170726_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='price_hotel',
            field=models.IntegerField(default=5000, validators=[django.core.validators.MinValueValidator(5000)]),
        ),
    ]
